import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { getCartItems } from "@/lib/db/actions";
import { CartProvider } from "@/components/cart/cart-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch cart items on the server side
  const cartPromise = getCartItems().then((result) => {
    if (typeof result === "function") {
      return result();
    }
    return result || [];
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} ${robotoSlab.variable} antialiased`}
      >
        <CartProvider cartPromise={cartPromise}>{children}</CartProvider>
      </body>
    </html>
  );
}
